package om.collection.map;

import java.util.HashMap;
import java.util.IdentityHashMap;
import java.util.Map;

//in identity hashmap hashcode is generated by object and not from content
// i.e here new String("key") does not generate hashcode key1 & key2 generates it

public class IdentityHashMapDemo {
	public static void main(String[] args) {
		
		String key1 = new String("key");
		String key2 = new String("key");
		
		Map<String, Integer> map = new HashMap<String, Integer>();
		Map<String, Integer> Identitymap = new IdentityHashMap<String, Integer>();
		
		map.put(key1, 1);
		map.put(key2, 2);
		Identitymap.put(key1, 1);
		Identitymap.put(key2, 2);
		
		
		System.out.println(map);
		System.out.println(Identitymap);
		
		System.out.println(key1.hashCode());
		System.out.println(key2.hashCode());
		System.out.println(System.identityHashCode(key1));
		System.out.println(System.identityHashCode(key2));
	}
}
